import * as dotenv from 'dotenv';
import { InitConfig } from './core/config.js';
import { InitCommands } from './commands/init.js';
import { InitLogger } from './core/logger.js';
import { InitDatabase } from './core/database.js';
import { InitDiscordClient, RegisterDiscordModule, DiscordClient } from './core/discord-client.js';
import { LevelingModule } from './modules/leveling.js';
import { DisboardModule } from './modules/disboard.js';
import { RolesModule } from './modules/roles.js';
import { NotifyModule } from './modules/notify.js';
import { AutoRole } from './modules/autoRole.js';

dotenv.config();
InitConfig();
InitLogger();
await InitDatabase();
InitDiscordClient();
RegisterDiscordModule(new NotifyModule());
RegisterDiscordModule(new LevelingModule());
RegisterDiscordModule(new DisboardModule());
RegisterDiscordModule(new AutoRole());
RegisterDiscordModule(RolesModule.instance);
InitCommands(DiscordClient);