import * as dotenv from 'dotenv';
import { InitConfig } from './core/config.ts';
import { InitCommands } from './commands/init.ts';
import { InitLogger } from './core/logger.ts';
import { InitDatabase } from './core/database.ts';
import { InitDiscordClient, RegisterDiscordModule, DiscordClient } from './core/discord-client.ts';
import { LevelingModule } from './modules/leveling.ts';
import { DisboardModule } from "./modules/disboard.ts";
import { RolesModule } from './modules/roles.ts';
import { NotifyModule } from './modules/notify.ts';
import { AutoRole } from './modules/autoRole.ts';

dotenv.config();
InitConfig();
InitLogger();
await InitDatabase();
InitDiscordClient();
RegisterDiscordModule(new NotifyModule());
RegisterDiscordModule(new LevelingModule());
RegisterDiscordModule(new DisboardModule());
RegisterDiscordModule(new AutoRole());
RegisterDiscordModule(RolesModule.instance);
InitCommands(DiscordClient);